set FLASK_APP=main.py 
set SECRET_KEY=this_is_secret_key_you_never_know
set DATABASE_URL=sqlite:///E:\Work\Code\Learn\python\flask\app.db
set MAIL_SERVER=localhost
set MAIL_PORT=8025
@REM set MAIL_USE_TLS=1
@REM set MAIL_USERNAME=
@REM set MAIL_PASSWORD=
set ADMINS=['admin@email.com']
set ELASTICSEARCH_URL=http://localhost:9200